/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/terms'
    | '/why-choose-us'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/terms'
    | '/why-choose-us'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/terms'
    | '/why-choose-us'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
